# Generated by Django 2.1.7 on 2019-03-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20190308_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='mob_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
